kind: ConfigMap
apiVersion: v1
metadata:
  name: huawei-csi-configmap
  namespace: kube-system
data:
  csi.json: |
    {
        "backends": [
            {
                "storage": "fusionstorage-san",
                "name": "***",
                "urls": ["https://*.*.*.*:28443"],
                "pools": ["***", "***"],
                "parameters": {"protocol": "iscsi", "portals": ["*.*.*.*", "*.*.*.*"]}
            }
        ]
    }
