kind: ConfigMap
apiVersion: v1
metadata:
  name: huawei-csi-configmap
  namespace: kube-system
data:
  csi.json: |
    {
        "backends": [
            {
                "storage": "oceanstor-nas",
                "name": "***",
                "urls": ["https://*.*.*.*:8088", "https://*.*.*.*:8088"],
                "pools": ["***", "***"],
                "parameters": {"protocol": "nfs", "portals": ["*.*.*.*"]}
            }
        ]
    }
